name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: yarn install

      - name: Create .env file
        run: |
          echo "VITE_CHAIN_ID=${{ secrets.VITE_CHAIN_ID_DEV }}" >> .env
          echo "VITE_TW_CLIENT_ID=${{ secrets.VITE_TW_CLIENT_ID }}" >> .env

      - name: Build project
        run: |
          yarn run build --mode development

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: DEV
      url: https://github.com/ashitosh-ownplay/cityverse-tycoon-nfts/dev-smart-wallet-nfts

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages-dev
